version: "3"
services:
  app:
   container_name: app
   build: .
   ports:
    - "9998:9998"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: server
    restart: always
    build: ./src/APIServer
    ports:
      - "3001:3001"
    links:
      - mongo
  

  

